# Drosera config for dry-run on Hoodi testnet
ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"

[trap]
source = "src/PriceDropTrap.sol:PriceDropTrap"
collect_function = "collect()"
should_respond_function = "shouldRespond(bytes[])"

[response]
source = "src/PriceDropResponse.sol:PriceDropResponse"
response_function = "onIncident(int256)"

collect_interval = "30s"

