version: 1

network:
  rpc: https://ethereum-hoodi-rpc.publicnode.com
  chainId: 31337   # Hoodi testnet chainId (example, replace with actual if needed)

trap:
  name: MintSpikeTrap
  address: "0xTRAP_CONTRACT_ADDRESS"     # replace after deploy
  artifact: "out/MintSpikeTrap.sol/MintSpikeTrap.json"

response:
  name: MintSpikeResponse
  address: "0xRESPONSE_CONTRACT_ADDRESS" # replace after deploy
  artifact: "out/MintSpikeResponse.sol/MintSpikeResponse.json"

settings:
  token: "0xMINTABLE_TOKEN_ADDRESS"      # your deployed mintable ERC20
  mintThreshold: "1000000000000000000000" # 1000 tokens (assuming 18 decimals)

dryrun:
  txs:
    - from: "0xYOUR_TEST_WALLET"
      to: "0xMINTABLE_TOKEN_ADDRESS"
      data: "0x40c10f1900000000000000000000000012340000000000000000000000000000000000000000000000003782dace9d9000000"
      # Encoded: mint(0x1234..., 10000000000000000000000)
      # This amount is > threshold, so trap should fire

