# Minimal Drosera config for dry-runs and wiring
[trap]
source = "src/PriceDropTrap.sol:PriceDropTrap"
collect_function = "collect()"
should_respond_function = "shouldRespond(bytes[])"

[response]
source = "src/PriceDropResponse.sol:PriceDropResponse"
response_function = "onIncident(int256)"

# Optional: how often the node should call collect() in real runs
collect_interval = "30s"
