# RPC endpoints
ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc  = "https://relay.hoodi.drosera.io"

# Hoodi testnet chain
eth_chain_id    = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.mintspiketrap]
# Path to the compiled trap artifact from forge build
path = "out/MintSpikeTrap.sol/MintSpikeTrap.json"

# For dryrun, this can be a placeholder — replace after you deploy a responder
response_contract = "0x0000000000000000000000000000000000000000"
# Adjust to match the function your responder will expose
response_function = "respond(bytes)"

# Trap parameters — tune for your tests
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 2
private_trap = true

# Use your Hoodi testnet wallet address here, or leave placeholder for dryrun
whitelist = ["0x04C4762BB1923c55Ea782967D4CA78f42B4E21E5"]

# Placeholder trap address (will change once you deploy it)
address = "0x0000000000000000000000000000000000000000"

