[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = { hoodi = "https://ethereum-hoodi-rpc.publicnode.com" }

[networks]
hoodi = { chain_id = 560048, url = "https://ethereum-hoodi-rpc.publicnode.com" }

# Dependencies
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "drosera-contracts/=lib/contracts/src/"
]

[fmt]
line_length = 100
tab_width = 4
