[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 120

remappings = [
    "forge-std/=lib/forge-std/src/",
    "drosera-contracts/=lib/contracts/src/"
]
