[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Modern remappings
remappings = [
    "contracts/=lib/contracts/src/",
    "forge-std/=lib/forge-std/src/"
]

# Optional Solidity compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
