[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Dependencies
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "drosera-contracts/=lib/contracts/src/"
]

[fmt]
line_length = 100
tab_width = 4
